name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  release_gate_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ArmorCode Release Gate
        id: armorcode_release_gate
        uses: armorcode/actions/release-gate-action@main 
        with:
          product: 'azure'
          subProduct: 'WebAppTeam'
          environment: 'production'
          mode: 'block' # or warn
          aql: 'scanType=SAST' # any additonal AQL parametes
          armorcode_token: ${{ secrets.ARMORCODE_API_TOKEN }} # Stored securely as a GitHub Secret
