name: ArmorCode Release Gate Test

on:
  workflow_dispatch:

jobs:
  release_gate_check:
    runs-on: ubuntu-latest
    steps:
    
      - name: Run ArmorCode Release Gate
        id: armorcode_release_gate
        uses: ChiragMyOrg/yummy/actions/release-gate-action@main
        with:
          product: 'azure'
          subProduct: 'juiceshop'
          environment: 'Production'
          mode: 'block' # try "warn" as well
          aql: 'scanType=SAST'
          armorcode_token: ${{ secrets.ARMORCODE_API_TOKEN }}
