name: ArmorCode Release Gate Test

env:
  armorcodehost: https://qa.armorcode.ai
  product: cm
  subProduct: cms
  environment: Production
  token: ${{secrets.ARMORCODE_TOKEN}}
  buildTool: GITHUB_ACTIONS
  buildNumber: 1
  end: 2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://qa.armorcode.ai/static/scripts/slastatus.sh 
          sh slastatus.sh
  release_gate_check:
    runs-on: ubuntu-latest
    steps:
      - name: Run ArmorCode Release Gate
        uses: ChiragMyOrg/actions/release-gate-action@main
        with:
          product: 'azure'
          subProduct: 'juiceshop'
          environment: 'Production'
          mode: 'block'
          aql: 'scanType=SAST'
          armorcode_token: ${{ secrets.ARMORCODE_API_TOKEN }}
