name: ArmorCode Release Gate
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  release_gate_check: # Update the job name as needed
    runs-on: ubuntu-latest
    permissions:
      checks: write     # For writing to the checks tab
      pull-requests: write  # For commenting on PRs
      contents: read    # For accessing repo content
    steps:  
      - name: Run ArmorCode Release Gate
        id: armorcode_gate
        uses: ChiragMyOrg/armorcode-actions/release-gate-action@main
        with:
          product: 'chirag'
          subProduct: 'cm'
          env: 'Production'
          armorcodeHost: 'https://qa.armorcode.ai'
          mode: 'warn'
          armorcodeAPIToken: ${{ secrets.ARMORCODE_API_TOKEN }}
          githubToken: ${{ github.token }}
          
