name: ArmorCode Release Gate
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  release_gate_check:
    runs-on: ubuntu-latest
    steps:
      - name: Run ArmorCode Release Gate
        uses: docker://public.ecr.aws/r4h5z0d3/armorcode-release-gate:latest
        with:
          product: 'heni'
          subProduct: 'test'
          env: 'Production'
          armorcodeHost: 'https://qa.armorcode.ai'
          mode: 'block'
          additionalAQLFilters: 'scanType=SAST'
          armorcodeAPIToken: ${{ secrets.ARMORCODE_API_TOKEN }}
          maxRetries: '5'
