name: ArmorCode
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  release_gate_check:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: Run ArmorCode Release Gate
        uses: ChiragMyOrg/armorcode-actions/release-gate-action@main
        with:
          product: 'bbcm'
          subProduct: 'bbscm'
          env: 'Production'
          api_url: 'https://qa.armorcode.ai'
          mode: 'block'
          additionalAQLFilters: 'scanType=SAST'
          armorcode_token: ${{ secrets.ARMORCODE_API_TOKEN }}
