name: ArmorCode

env:
  armorcodehost: https://qa.armorcode.ai
  product: bbcm
  subProduct: bbscm
  environment: Production
  token: ${{secrets.ARMORCODE_API_TOKEN}}
  buildTool: GITHUB_ACTIONS
  buildNumber: ${{github.run_number}}
  end: 10
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://qa.armorcode.ai/static/scripts/slastatus.sh
          echo "✅ Successfully fetched slastatus.sh from ArmorCode"
          sh slastatus.sh
