name: ArmorCode
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: Run ArmorCode Release Gate
        uses: ChiragMyOrg/armorcode-actions/release-gate-action@main
        with:
          group_name: 'bbcm'
          sub_group_name: 'bbscm'
          environment: 'Production'
          mode: 'block'
          aql: 'scanType=SAST'
          armorcode_token: ${{ secrets.ARMORCODE_API_TOKEN }}
